Project_1/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'encyclopedia'

urlpatterns = [
    path("", views.index, name='index'),
    path('new/', views.new_entry, name='new'),
    path('wiki/<str:name>/', views.entry, name='entry'),
    path('edit/<str:name>/', views.edit, name='edit'),
    path('random/', views.random_entry, name='random'),
    path('search/', views.search, name='search'),
]

Project_1/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls", namespace='encylopedia'))
]

Project_1/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

Project_1/wiki/encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.files.storage import default_storage
from django.urls import reverse
from django.contrib import messages
import random

from . import util


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

# Entry page: /wiki/TITLE should take user to an entry with that TITLE
# Rework index page to have links to entries


def entry(request, name):
    if name not in util.list_entries():
        messages.error(request, 'Entry does not exist.')
        return HttpResponseRedirect(reverse('encyclopedia:index'))
    util.convert(name, 'encyclopedia/templates/encyclopedia/entry.html')
    return render(request, "encyclopedia/entry.html", {'name': name})

# New page: Enter markdown data in a textarea field with a save button at the bottom,
# check to make sure the entry does not already exist, then save to disk as a new markdown entry


def new_entry(request):
    if request.method == 'POST':
        title = request.POST['title']
        content = request.POST['content']
        if title in util.list_entries():
            messages.error(request, 'Entry already exists')
            return HttpResponseRedirect(reverse('encyclopedia:new'))
        f = default_storage.open(f'entries/{title}.md', 'w+')
        f.write(content)
        return HttpResponseRedirect(reverse('encyclopedia:entry', args=[title]))
    else:
        return render(request, 'encyclopedia/new_entry.html')

# Edit page that pulls up existing data and has a save button


def edit(request, name):
    f = default_storage.open(f'entries/{name}.md', 'r+')
    content = f.read()
    if request.method == 'POST':
        edited = request.POST['edited']
        f.seek(0)
        f.write(edited)
        f.truncate()
        return HttpResponseRedirect(reverse('encyclopedia:entry', args=[name]))
    elif request.method == 'GET':
        return render(request, 'encyclopedia/edit.html', {
            'name': name, 'content': content
        })

# Random page button


def random_entry(request):
    entries = util.list_entries()
    number = random.randint(0, len(entries))
    page = entries[(number - 1)]
    return HttpResponseRedirect(reverse('encyclopedia:entry', args=[page]))

# Search feature that takes into account partial strings by listing entries with that partial string


def search(request):
    q = request.GET['q']
    if q in util.list_entries():
        return HttpResponseRedirect(reverse('encyclopedia:entry', args=[q]))
    else:
        possibles = []
        for page in util.list_entries():
            if q in page:
                possibles.append(page)
            else:
                continue
        if possibles == []:
            messages.error(request, 'No entries match your search.')
            return HttpResponseRedirect(reverse('encyclopedia:index'))
        else:
            return render(request, 'encyclopedia/search.html', {
                'results': possibles
            })

Project_1/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends 'encyclopedia/layout.html' %}

{% block body %}
<h1>{{ name }}</h1>
<form action="{% url 'encyclopedia:edit' name %}" method="post">
    {% csrf_token %}
    <textarea name="edited">{{ content }}</textarea>
    <button type="submit">Save Changes</button>
</form>
{% endblock %}

Project_1/wiki/encyclopedia/templates/encyclopedia/entry.html
        {% extends 'encyclopedia/layout.html' %}

        {% block body %}
        <h1>Python</h1>
<p></p>
<p>Python is a programming language that can be used both for writing <strong>command-line scripts</strong> or building <strong>web applications</strong>.</p>
<div><a href="{% url 'encyclopedia:edit' name %}">Edit</a></div>
    {% endblock %}
    

Project_1/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
<h1>All Entries</h1>

<ul>
    {% for entry in entries %}
    <li>
        <a href="{% url 'encylopedia:entry' entry %}">{{ entry }}</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

Project_1/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
</head>

<style>
    .error {
        background-color: rgb(218, 110, 110);
        padding: 10px;
    }
</style>

<body>
    <div class="row">
        <div class="sidebar col-lg-2 col-md-3">
            <h2>Wiki</h2>
            <form action="{% url 'encyclopedia:search' %}">
                <input class="search" type="text" name="q" placeholder="Search Entries">
            </form>
            <div>
                <a href="{% url 'encyclopedia:index' %}">Home</a>
            </div>
            <div>
                <a href="{% url 'encyclopedia:new' %}">Create New Page</a>
            </div>
            <div>
                <a href="{% url 'encylopedia:random' %}">Random Page</a>
            </div>
            {% block nav %}
            {% endblock %}
        </div>
        <div class="main col-lg-10 col-md-9">
            {% if messages %}
            {% for message in messages %}
            <div class="error">{{ message }}</div>
            {% endfor %}
            {% endif %}
            {% block body %}
            {% endblock %}
        </div>
    </div>

</body>

</html>

Project_1/wiki/encyclopedia/templates/encyclopedia/new_entry.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
<style>
    .error {
        background-color: rgb(218, 110, 110);
        padding: 10px;
    }
</style>
<h1>New Entry</h1>
<form action="{% url 'encylopedia:new' %}" method="post">
    {% csrf_token %}
    {% if messages %}
    {% for message in messages %}
    <div class="error">{{ message }}</div>
    {% endfor %}
    {% endif %}
    <div>
        <input type="text" name="title" placeholder="Title">
    </div>
    <div>
        <textarea name="content" placeholder="Enter Markdown text here"></textarea>
    </div>
    <button type="submit">Save</button>
</form>
{% endblock %}

Project_1/wiki/encyclopedia/templates/encyclopedia/search.html
{% extends 'encyclopedia/layout.html' %}

{% block body %}
<div>
    <h3>Possible Matches:</h3>
</div>
<div>
    <ul>
        {% for result in results %}
        <li><a href="{% url 'encyclopedia:entry' result%}">{{ result }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}